SELECT p.nome AS NomeProduto,p.tipo AS TipoProduto,p.unidade_venda AS UnidadeVenda,pp.preco AS Preco,pp.quantidade_disponivel AS QuantidadeDisponivel FROM Produto_Produtor pp JOIN Produto p ON pp.id_produto = p.id_produto JOIN Produtor pr ON pp.id_produtor = pr.id_produtor WHERE pr.nome = 'Fazenda Orgânica da Serra' ORDER BY NomeProduto;

SELECT ped.id_pedido,ped.data_pedido,ped.status,f.data AS DataFeira,f.local_entrega AS LocalEntregaFeira,p.nome AS NomeProduto,pr.nome AS NomeProdutor,pp.quantidade AS QuantidadePedida,(pp.quantidade * ppr.preco) AS SubtotalItem FROM Pedido_Produto pp JOIN Pedido ped ON pp.id_pedido = ped.id_pedido JOIN Consumidor c ON ped.id_consumidor = c.id_consumidor JOIN Feira f ON ped.id_feira = f.id_feira JOIN Produto p ON pp.id_produto = p.id_produto JOIN Produtor pr ON pp.id_produtor = pr.id_produtor JOIN Produto_Produtor ppr ON pp.id_produto = ppr.id_produto AND pp.id_produtor = ppr.id_produtor WHERE c.nome = 'Ana Silva' ORDER BY ped.data_pedido,ped.id_pedido,NomeProduto;

SELECT ped.id_pedido,c.nome AS NomeConsumidor,ped.data_pedido,ped.status,SUM(pp.quantidade * ppr.preco) AS ValorTotalPedido FROM Pedido_Produto pp JOIN Pedido ped ON pp.id_pedido = ped.id_pedido JOIN Produto_Produtor ppr ON pp.id_produto = ppr.id_produto AND pp.id_produtor = ppr.id_produtor JOIN Consumidor c ON ped.id_consumidor = c.id_consumidor GROUP BY ped.id_pedido,c.nome,ped.data_pedido,ped.status ORDER BY ped.id_pedido;

SELECT p.nome AS NomeProduto,p.tipo AS TipoProduto,SUM(pp.quantidade) AS QuantidadeTotalPedida FROM Pedido_Produto pp JOIN Pedido ped ON pp.id_pedido = ped.id_pedido JOIN Feira f ON ped.id_feira = f.id_feira JOIN Produto p ON pp.id_produto = p.id_produto WHERE f.data = (SELECT MAX(data) FROM Feira WHERE data <= CURDATE()) GROUP BY p.nome,p.tipo ORDER BY QuantidadeTotalPedida DESC LIMIT 5;

SELECT pr.nome AS NomeProdutor,f.data AS DataFeira,COUNT(DISTINCT ped.id_pedido) AS TotalPedidos FROM Produtor pr JOIN Produto_Produtor ppr ON pr.id_produtor = ppr.id_produtor JOIN Pedido_Produto pprod ON ppr.id_produto = pprod.id_produto AND ppr.id_produtor = pprod.id_produtor JOIN Pedido ped ON pprod.id_pedido = ped.id_pedido JOIN Feira f ON ped.id_feira = f.id_feira GROUP BY pr.nome,f.data HAVING COUNT(DISTINCT ped.id_pedido) > 3 ORDER BY TotalPedidos DESC;
